"""
profile_optimization_sweep.py — Exhaustive velocity-profile search for the
Hydraix I FCEV (SEM Poland, Silesia Ring).

Goal: determine which velocity-profile FAMILY gives the best mileage (km/m3 H2)
under the race constraints, and conclude whether the current pulse-and-glide
(PnG) profile is optimal or whether a different family beats it.

Method
------
* REUSE the validated plant + physics from combined_best_profile.py:
    - measured motor efficiency map (motor_eff_rpm_torque.xlsx, 'Efficiency Lookup')
      via compute_motor_signals() -> P_dem (motor electrical),
    - simulate() (DC-DC eta, SC round-trip loss, FC ramp/floor, SOC),
    - km_per_m3() with charge-sustaining (CS) normalisation,
    - Strategy G auto-tuned to charge-sustaining for EVERY candidate (bisect_kp),
      so the EMS comparison is apples-to-apples.
* The PnG family reuses build_profile() exactly.
* Constant-cruise / gentle-accel / elevation-adaptive families are generated by a
  NEW finite-state profile builder in THIS file that obeys the SAME constraints
  (full stop every lap, no regen -> coast then hard-brake from V_COAST_STOP, 35 Nm
  motor torque cap, 14.5 km / 11 laps, <=35 min).

Constraints checked by verify(): distance > 14.5 km, 28-35.5 min, exactly 11 stops.

Outputs
-------
* console: ranked table of all candidate profiles (km/m3, H2, dSOC, CS, time,
  cruise/peak speed, motor high-eta time fraction, energy breakdown),
* plots/profile_optimization.png: winning v(t)+elevation + km/m3 ranking bar chart.
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import numpy as np
import matplotlib; matplotlib.use('Agg')
import matplotlib.pyplot as plt
from scipy.signal import savgol_filter

import combined_best_profile as C
from combined_best_profile import (
    build_profile, compute_motor_signals, verify, simulate, km_per_m3,
    make_strat_g, bisect_kp, motor_eta_rt,
    D_LAP, DT, N_LAPS, V_MAX, V_COAST_STOP, A_HARD, N_STOP_STEPS,
    TAU_MOTOR_MAX, R_WHEEL, MASS, G, CD, AF, CRR, RHO, ETA_DT,
    GRADE_THRESH, P_RAMP_MAX, RPM_PER_MS,
    _grade_fn, _elev_fn, _net_force, _coast_dist, _hold_power,
)
from ems_core import SC_ETA, ETA_DCDC

# ───────────────────────────────────────────────────────────────────────────────
# Generic constant-cruise / gentle-accel / elevation-adaptive profile builder.
# Same physics & terminal-stop logic as combined_best_profile._build_lap, but the
# in-lap target is a CRUISE SPEED held by a closed-loop power command rather than
# a pulse/glide band. This lets us express families B/C/D/E.
# ───────────────────────────────────────────────────────────────────────────────

def _cruise_power(v, vtarget, grade, a_cap):
    """Electrical power to track a cruise target: hold load + bounded accel term.
    Commands accel up to a_cap toward vtarget; coasts (P=0) when at/above target."""
    if v >= vtarget - 0.05:
        # hold speed (no accel) — pure road load
        return _hold_power(v, grade)
    # accelerate gently toward target
    a_need = min(a_cap, (vtarget - v) / max(DT, 0.2))
    F = 0.5*CD*AF*RHO*v*v + CRR*MASS*G + MASS*G*grade + MASS*a_need
    # Convert the desired tractive FORCE to a power command. P = F·v underflows to
    # zero at standstill (so the car would never launch); floor the speed at the
    # SAME 0.3 m/s that _net_force uses for P·η/max(v,0.3), so the commanded power
    # reproduces F (capped at the motor's F_max) right down to v=0.
    return max(0., F*max(v, 0.3)/ETA_DT)


def _build_lap_cruise(v_cruise, a_accel, k_grade=0., const_power=None):
    """One lap: gentle accel -> hold cruise -> coast -> hard-brake to a stop.

    v_cruise   : steady cruise speed [m/s] (flat-road target).
    a_accel    : max acceleration during the launch ramp [m/s^2].
    k_grade    : elevation-adaptive gain. >0 lowers target on climbs / raises on
                 descents (ease off uphill, let it run downhill). 0 = flat target.
    const_power: if not None, command CONSTANT electrical power [W] during the
                 cruise phase instead of constant speed (family E). Speed then
                 floats with grade; capped at V_MAX.
    """
    tl=[];vl=[];Pl=[];sl=[];el=[];gl=[];coastl=[]
    t=v=s=0.; first=True; pP=0.; mode='ACCEL'
    while True:
        sw=s%D_LAP; grade=float(_grade_fn(sw)); elev=float(_elev_fn(sw))
        v_tg=float(np.clip(v_cruise - k_grade*grade, 3.0, V_MAX))
        rem=D_LAP-sw; Pt=0.; vc=V_MAX
        # terminal stop: coast when remaining == natural coast dist; hard-brake below V_COAST_STOP
        if mode not in ('COAST_TO_STOP','HARD_BRAKE') and v>0 and rem<800.:
            if rem<=_coast_dist(v,s): mode='COAST_TO_STOP'
        if mode=='COAST_TO_STOP' and v<=V_COAST_STOP: mode='HARD_BRAKE'

        if mode in ('COAST_TO_STOP','HARD_BRAKE'):
            Pt=0.; vc=V_MAX
        elif const_power is not None and v>= (v_tg-0.5):
            # constant-power cruise: command fixed electrical power, speed floats
            Pt=float(const_power); vc=V_MAX; mode='CRUISE_CP'
        else:
            Pt=_cruise_power(v, v_tg, grade, a_accel)
            vc=v_tg if v < v_tg else V_MAX
            mode='ACCEL' if v < v_tg-0.05 else 'CRUISE'

        P=float(np.clip(Pt,pP-P_RAMP_MAX,pP+P_RAMP_MAX)); pP=P
        if not first:
            tl.append(t);vl.append(v);Pl.append(P);sl.append(sw)
            el.append(elev);gl.append(grade)
            coastl.append(mode in ('COAST_TO_STOP','HARD_BRAKE'))
        first=False
        if mode=='HARD_BRAKE':
            vn=max(0.,v-A_HARD*DT); sn=s+v*DT
        else:
            a=_net_force(v,P,grade)/MASS
            vn=float(np.clip(v+a*DT,0.,vc)); sn=s+v*DT
        t+=DT; v=vn; s=sn
        if (mode=='HARD_BRAKE' and v==0.) or t>800.: break
    se=sl[-1] if sl else 0.; ee=el[-1] if el else float(_elev_fn(0)); ge=gl[-1] if gl else 0.
    for _ in range(N_STOP_STEPS):
        tl.append(t);vl.append(0.);Pl.append(0.);sl.append(se)
        el.append(ee);gl.append(ge);coastl.append(True);t+=DT
    return tl,vl,Pl,sl,el,gl,coastl


def build_profile_cruise(v_cruise, a_accel, k_grade=0., const_power=None):
    """Tile the cruise lap over 11 laps; smooth velocity like build_profile()."""
    at=[];av=[];aP=[];as_=[];aln=[];ae=[];ag=[];ac=[]; to=0.
    for lap in range(1,N_LAPS+1):
        tl,vl,Pl,sl,el,gl,coastl=_build_lap_cruise(v_cruise,a_accel,k_grade,const_power)
        ta=np.array(tl)+to
        at.append(ta);av.append(np.array(vl));aP.append(np.array(Pl))
        as_.append(np.array(sl));aln.append(np.full(len(tl),lap,dtype=int))
        ae.append(np.array(el));ag.append(np.array(gl))
        ac.append(np.array(coastl,dtype=bool)); to=float(ta[-1])+DT
    ta=np.concatenate(at);va=np.concatenate(av);Pa=np.concatenate(aP)
    sa=np.concatenate(as_);la=np.concatenate(aln);ea=np.concatenate(ae)
    ga=np.concatenate(ag);ca=np.concatenate(ac)
    vs=va.copy(); im=(va>0.)
    ss=np.where(np.diff(np.concatenate([[0],im.astype(int)]))==1)[0]
    se_=np.where(np.diff(np.concatenate([im.astype(int),[0]]))==-1)[0]+1
    for ms,me in zip(ss,se_):
        seg=va[ms:me]
        if len(seg)>25: vs[ms:me]=savgol_filter(seg,21,2)
        vs[ms:me]=np.clip(vs[ms:me],0.,V_MAX)
    return ta,vs,Pa,sa,la,ea,ga,ca


# ───────────────────────────────────────────────────────────────────────────────
# Scoring: run Strategy G auto-tuned to CS, compute km/m3 + diagnostics.
# ───────────────────────────────────────────────────────────────────────────────

def _motor_eta_stats(va, ga):
    """Time fraction the motor spends in high-eta (>=0.80) vs low-eta region, and
    mean motor eta weighted by motor-on time. Uses the measured map exactly as the
    plant does (compute_motor_signals)."""
    accel = np.gradient(va, DT)
    P_wheel = (CRR*MASS*G*va + 0.5*CD*AF*RHO*va**3 + MASS*accel*va + MASS*G*ga*va)
    P_wheel_pos = np.maximum(P_wheel, 0.)
    v_safe = np.maximum(va, 0.3)
    Torque = (P_wheel_pos / v_safe) * R_WHEEL
    RPM = va * RPM_PER_MS
    moving = (P_wheel_pos > 1.0) & (va > 0.3)
    eta = motor_eta_rt(RPM, Torque)
    eta_on = eta[moving]
    if len(eta_on) == 0:
        return 0., 0., 0.
    f_hi = float(np.mean(eta_on >= 0.80))
    return float(np.mean(eta_on)), f_hi, float(np.sum(moving)*DT)


def _energy_breakdown(va, ga, ca):
    """Decompose where mechanical energy goes over the whole race [Joules].
    aero, rolling, the 11 brake KE losses (no regen), and net grade (~0 on a loop)."""
    accel = np.gradient(va, DT)
    E_aero = float(np.sum(0.5*CD*AF*RHO*va**3) * DT)
    E_roll = float(np.sum(CRR*MASS*G*va) * DT)
    E_grade = float(np.sum(MASS*G*ga*va) * DT)
    # brake KE loss: KE at the instant hard-brake begins, summed over laps.
    # detect transitions into braking by velocity going to 0 while coasting flagged.
    # simpler & robust: sum positive KE dissipated where decel happens during ca
    # (coast+brake) — but coast aero/roll is already counted; the *brake* loss is
    # the residual KE dumped when the car is forced to 0. Compute per-lap as KE at
    # V_COAST_STOP times number of stops (hard-brake from V_COAST_STOP).
    KE_brake = 0.5*MASS*V_COAST_STOP**2 * N_LAPS
    return dict(E_aero=E_aero, E_roll=E_roll, E_grade=E_grade, KE_brake=KE_brake)


def score_profile(name, family, params, ta, va, Pa, sa, la, ea, ga, ca, verbose=True):
    ok, d, dur, stops = verify(ta, va, la)
    if not ok:
        if verbose:
            print(f"  [INVALID] {name:32s} d={d:.2f}km dur={dur:.1f}min stops={stops}")
        return None
    P_e, _, _ = compute_motor_signals(va, ga)
    Kp, r = bisect_kp(P_e, la, ca, name)
    km3 = km_per_m3(r)
    cs = abs(r['dSOC']) <= 0.015
    mean_eta, f_hi, t_on = _motor_eta_stats(va, ga)
    eb = _energy_breakdown(va, ga, ca)
    # FC electrical energy actually delivered (proxy for H2 path)
    E_fc = r['E_fc_J']
    peak_v = float(np.max(va))
    cruise_v = float(np.median(va[va > 0.5*peak_v])) if peak_v > 0 else 0.
    rec = dict(name=name, family=family, params=params, km3=km3, H2=r['m_H2'],
               H2n=r['m_H2_norm'], dSOC=r['dSOC'], cs=cs, dur=dur, dist=d,
               peak_v=peak_v, cruise_v=cruise_v, mean_eta=mean_eta, f_hi=f_hi,
               t_on=t_on, E_fc=E_fc, Kp=Kp,
               ta=ta, va=va, Pa=Pa, sa=sa, la=la, ea=ea, ga=ga, ca=ca,
               SOC=r['SOC'], Pfc=r['Pfc'], Psc=r['Psc'], **eb)
    if verbose:
        flag = 'CS ' if cs else 'no '
        print(f"  >>> {name:32s} km/m3={km3:6.1f}  H2={r['m_H2']:.3f}g  dSOC={r['dSOC']:+.4f} "
              f"[{flag}] dur={dur:.1f}m vmax={peak_v*3.6:.1f}km/h eta_m={mean_eta*100:.1f}% f_hi={f_hi*100:.0f}%")
    return rec


# ───────────────────────────────────────────────────────────────────────────────
# Sweep definitions
# ───────────────────────────────────────────────────────────────────────────────

def run_sweeps():
    results = []

    print("\n" + "="*78)
    print("FAMILY A — Pulse-and-Glide (current). Includes the documented baseline.")
    print("="*78)
    V_DH = 10.5
    # baseline validation point first (VH=10/VL=6/PP=1400):
    png_grid = []
    png_grid.append((10.0, 6.0, 1400., 0.))   # documented ~235 baseline
    for VH in [9.5, 10.0, 10.5, 11.0]:
        for VL in [5.5, 6.0, 6.5, 7.0]:
            if VL >= VH-1.5: continue
            for PP in [1200., 1400., 1600.]:
                png_grid.append((VH, VL, PP, 0.))
    # elevation-adaptive PnG (family D within PnG): k_grade band-shift
    for kg in [40., 80., 120.]:
        png_grid.append((9.5, 7.0, 1200., kg))
    seen=set()
    for VH, VL, PP, kg in png_grid:
        key=(VH,VL,PP,kg)
        if key in seen: continue
        seen.add(key)
        ta,va,Pa,sa,la,ea,ga,ca = build_profile(VH,VL,V_DH,PP,1200.,k_grade=kg)
        nm=f"PnG VH{VH} VL{VL} PP{PP:.0f}"+(f" kg{kg:.0f}" if kg else "")
        fam='A-PnG' if kg==0 else 'D-PnG-elev'
        rec=score_profile(nm, fam, dict(VH=VH,VL=VL,PP=PP,k_grade=kg),
                          ta,va,Pa,sa,la,ea,ga,ca)
        if rec: results.append(rec)

    print("\n" + "="*78)
    print("FAMILY B/C — Constant-cruise + coast-to-stop (gentle vs brisk accel).")
    print("="*78)
    for vcr in [7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 10.0, 11.0]:
        for a in [0.25, 0.5, 1.0, 2.0]:   # gentle -> brisk launch
            ta,va,Pa,sa,la,ea,ga,ca = build_profile_cruise(vcr, a)
            nm=f"Cruise v{vcr} a{a}"
            rec=score_profile(nm,'BC-cruise',dict(v_cruise=vcr,a_accel=a),
                              ta,va,Pa,sa,la,ea,ga,ca)
            if rec: results.append(rec)

    print("\n" + "="*78)
    print("FAMILY D — Elevation-adaptive constant-cruise (modulate target by grade).")
    print("="*78)
    for vcr in [8.0, 8.5, 9.0]:
        for kg in [60., 120., 200.]:
            ta,va,Pa,sa,la,ea,ga,ca = build_profile_cruise(vcr, 0.5, k_grade=kg)
            nm=f"CruiseElev v{vcr} kg{kg:.0f}"
            rec=score_profile(nm,'D-cruise-elev',dict(v_cruise=vcr,k_grade=kg),
                              ta,va,Pa,sa,la,ea,ga,ca)
            if rec: results.append(rec)

    print("\n" + "="*78)
    print("FAMILY E — Constant-POWER cruise (speed floats with grade).")
    print("="*78)
    for pwr in [350., 450., 550., 650.]:
        for vcr in [8.5, 9.5]:
            ta,va,Pa,sa,la,ea,ga,ca = build_profile_cruise(vcr, 0.5, const_power=pwr)
            nm=f"ConstPwr P{pwr:.0f} vcap{vcr}"
            rec=score_profile(nm,'E-const-power',dict(P=pwr,v_cap=vcr),
                              ta,va,Pa,sa,la,ea,ga,ca)
            if rec: results.append(rec)

    return results


def main():
    results = run_sweeps()
    if not results:
        raise RuntimeError("No valid profiles found.")

    # rank: prefer CS, then km/m3
    valid_cs = [r for r in results if r['cs']]
    ranked = sorted(valid_cs or results, key=lambda r: -r['km3'])

    print("\n" + "="*100)
    print("RANKED TABLE (charge-sustaining only)" + ("" if valid_cs else "  [no CS runs — showing all]"))
    print("="*100)
    hdr = f"{'#':>2} {'profile':34s} {'family':14s} {'km/m3':>7} {'H2[g]':>7} {'dSOC':>8} {'dur':>5} {'vmax':>6} {'eta_m':>6} {'f_hi':>5}"
    print(hdr)
    print("-"*100)
    for i, r in enumerate(ranked[:15], 1):
        print(f"{i:>2} {r['name']:34s} {r['family']:14s} {r['km3']:7.1f} {r['H2']:7.3f} "
              f"{r['dSOC']:+8.4f} {r['dur']:5.1f} {r['peak_v']*3.6:6.1f} "
              f"{r['mean_eta']*100:6.1f} {r['f_hi']*100:5.0f}")

    best = ranked[0]
    # find best PnG and best cruise for the verdict margin
    png = [r for r in (valid_cs or results) if r['family'] in ('A-PnG','D-PnG-elev')]
    cruise = [r for r in (valid_cs or results) if r['family'] in ('BC-cruise','D-cruise-elev','E-const-power')]
    best_png = max(png, key=lambda r: r['km3']) if png else None
    best_cruise = max(cruise, key=lambda r: r['km3']) if cruise else None

    print("\n" + "="*100)
    print("VERDICT")
    print("="*100)
    if best_png:
        print(f"Best PnG    : {best_png['name']:34s} km/m3={best_png['km3']:.1f}  "
              f"eta_m={best_png['mean_eta']*100:.1f}%  f_hi={best_png['f_hi']*100:.0f}%")
    if best_cruise:
        print(f"Best cruise : {best_cruise['name']:34s} km/m3={best_cruise['km3']:.1f}  "
              f"eta_m={best_cruise['mean_eta']*100:.1f}%  f_hi={best_cruise['f_hi']*100:.0f}%")
    if best_png and best_cruise:
        margin = best_png['km3'] - best_cruise['km3']
        winner = "PULSE-AND-GLIDE" if margin > 0 else "CONSTANT-CRUISE"
        print(f"\nWINNER: {winner}  (margin = {abs(margin):.1f} km/m3, "
              f"{abs(margin)/max(best_cruise['km3'],best_png['km3'])*100:.1f}%)")

    print("\nEnergy breakdown of overall best profile (whole race, mechanical J):")
    tot = best['E_aero']+best['E_roll']+best['KE_brake']+max(best['E_grade'],0)
    print(f"  aero drag    : {best['E_aero']/1000:8.1f} kJ ({best['E_aero']/tot*100:4.1f}%)")
    print(f"  rolling res. : {best['E_roll']/1000:8.1f} kJ ({best['E_roll']/tot*100:4.1f}%)")
    print(f"  brake KE loss: {best['KE_brake']/1000:8.1f} kJ ({best['KE_brake']/tot*100:4.1f}%) (11 stops, no regen)")
    print(f"  net grade    : {best['E_grade']/1000:8.1f} kJ (loop ~0)")
    print(f"  FC elec energy delivered (race): {best['E_fc']/1000:.1f} kJ")

    # ── Figure ──────────────────────────────────────────────────────────────────
    fig = plt.figure(figsize=(15, 11), dpi=130)
    gs = fig.add_gridspec(2, 1, height_ratios=[1.1, 1.0], hspace=0.32)

    # winning velocity profile (lap 1) + elevation
    ax = fig.add_subplot(gs[0]); axe = ax.twinx()
    m1 = best['la'] == 1
    t1 = best['ta'][m1]-best['ta'][m1][0]
    v1 = best['va'][m1]*3.6
    e1 = best['ea'][m1]
    # also overlay the best of the OTHER family for contrast
    other = best_cruise if best['family'].startswith(('A','D-PnG')) else best_png
    ax.plot(t1, v1, color='#D55E00', lw=2.2, label=f"WINNER: {best['name']} ({best['km3']:.1f} km/m3)")
    if other is not None:
        mo = other['la']==1
        to=other['ta'][mo]-other['ta'][mo][0]; vo=other['va'][mo]*3.6
        ax.plot(to, vo, color='#0072B2', lw=1.6, ls='--', alpha=0.8,
                label=f"Best other: {other['name']} ({other['km3']:.1f} km/m3)")
    axe.fill_between(t1, e1, np.min(e1), color='#BB3311', alpha=0.12)
    axe.plot(t1, e1, color='#BB3311', lw=0.9, alpha=0.5)
    axe.set_ylabel('Elevation [m]', color='#BB3311', fontsize=10)
    ax.set_xlabel('Time in lap [s]', fontsize=11)
    ax.set_ylabel('Velocity [km/h]', fontsize=11)
    ax.set_title('Winning velocity profile vs best alternative family (Lap 1) + elevation',
                 fontsize=12, fontweight='bold')
    ax.legend(loc='upper right', fontsize=9)
    ax.grid(alpha=0.25)

    # km/m3 ranking bar chart (top ~12)
    ax2 = fig.add_subplot(gs[1])
    top = ranked[:12]
    names = [r['name'] for r in top]
    vals = [r['km3'] for r in top]
    fam_color = {'A-PnG':'#D55E00','D-PnG-elev':'#E69F00','BC-cruise':'#0072B2',
                 'D-cruise-elev':'#56B4E9','E-const-power':'#009E73'}
    cols = [fam_color.get(r['family'], '#888') for r in top]
    y = np.arange(len(top))
    ax2.barh(y, vals, color=cols)
    ax2.set_yticks(y); ax2.set_yticklabels(names, fontsize=8)
    ax2.invert_yaxis()
    ax2.set_xlabel('km / m3 H2 (CS-normalised)', fontsize=11)
    ax2.set_title('Top profiles across all families (color = family)', fontsize=12, fontweight='bold')
    for i, v in enumerate(vals):
        ax2.text(v+0.3, i, f"{v:.1f}", va='center', fontsize=8)
    ax2.set_xlim(min(vals)-5, max(vals)+6)
    handles = [plt.Rectangle((0,0),1,1,color=c) for c in fam_color.values()]
    ax2.legend(handles, list(fam_color.keys()), fontsize=8, loc='lower right')
    ax2.grid(alpha=0.25, axis='x')

    out = os.path.join(C.RESULTS_DIR, 'profile_optimization.png')
    fig.savefig(out, dpi=130, bbox_inches='tight', facecolor='white')
    plt.close(fig)
    print(f"\nFigure -> {out}")
    print("\nDONE.")


if __name__ == '__main__':
    main()
